---
- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes

- name: Set ownership of WordPress files
  file:
    path: /var/www/wordpress
    owner: www-data
    group: www-data
    recurse: yes

- name: Create WordPress config file from wp-config-sample.php
  command: cp /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php
  args:
    creates: /var/www/wordpress/wp-config.php

- name: Update WordPress config file
  replace:
    path: /var/www/wordpress/wp-config.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: "database_name_here", replace: "{{ wordpress_db_name }}" }
    - { regexp: "username_here", replace: "{{ wordpress_db_user }}" }
    - { regexp: "password_here", replace: "{{ wordpress_db_password }}" }

- name: Configure Apache virtual host for WordPress
  template:
    src: wordpress.conf.j2
    dest: /etc/apache2/sites-available/wordpress.conf

- name: Disable default Apache site
  command: a2dissite 000-default.conf
  ignore_errors: yes
  notify: reload apache

- name: Enable WordPress site
  command: a2ensite wordpress.conf
  notify: restart apache

- name: Ensure .htaccess exists and is writable
  file:
    path: /var/www/wordpress/.htaccess
    state: touch
    owner: www-data
    group: www-data
    mode: '0644'