---
- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Install MySQL Python dependency
  apt:
    name: python3-mysqldb
  when: ansible_os_family == "Debian"

- name: Start and enable MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create WordPress database
  mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    # Не указываем пароль — используем socket auth

- name: Create WordPress DB user
  mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_password }}"
    priv: "{{ wordpress_db_name }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root